name: Java CI

on: [ push, pull_request ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build Docker image
        run: |
          docker build -t pcanohuoc/gateway-management:latest \
            --build-arg JAR_FILE=build/libs/*.jar \
            .

      - name: Publish Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push pcanohuoc/gateway-management:latest

      - name: Publish to GitHub Packages
        run: ./gradlew publish
